"""
DAW Engine - Professional AI-Powered Music Production Studio

A musician-focused system that generates individual instrument parts
with precise musical control. Think of it as a DAW where each track
is generated by AI instead of recorded.

Key Concepts:
  - PART: A single instrument part (e.g., "808 bass for 8 bars")
  - PROJECT: Collection of parts that form a song
  - MEMORY: Relational context between parts for coherence
"""

import json
import os
import pickle
import shutil
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from typing import Optional, Dict, List, Tuple, Any
import numpy as np

# Import MusicGen backend (optional)
try:
    from modern_ai_generator import MusicGenGenerator, AudioAnalyzer
    MUSICGEN_AVAILABLE = True
except ImportError:
    MUSICGEN_AVAILABLE = False
    print("Warning: MusicGen not available. Install transformers torchaudio")

try:
    import soundfile as sf
    SOUNDFILE_AVAILABLE = True
except ImportError:
    SOUNDFILE_AVAILABLE = False

# ============================================================
# MUSICAL THEORY CONSTANTS
# ============================================================

SCALE_PATTERNS = {
    "major":            [0, 2, 4, 5, 7, 9, 11],
    "natural_minor":    [0, 2, 3, 5, 7, 8, 10],
    "harmonic_minor":   [0, 2, 3, 5, 7, 8, 11],
    "melodic_minor":    [0, 2, 3, 5, 7, 9, 11],
    "dorian":           [0, 2, 3, 5, 7, 9, 10],
    "phrygian":         [0, 1, 3, 5, 7, 8, 10],
    "lydian":           [0, 2, 4, 6, 7, 9, 11],
    "mixolydian":       [0, 2, 4, 5, 7, 9, 10],
    "aeolian":          [0, 2, 3, 5, 7, 8, 10],
    "locrian":          [0, 1, 3, 5, 6, 8, 10],
    "blues":            [0, 3, 5, 6, 7, 10],
    "major_pentatonic": [0, 2, 4, 7, 9],
    "minor_pentatonic": [0, 3, 5, 7, 10],
    "chromatic":        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    "whole_tone":       [0, 2, 4, 6, 8, 10],
    "diminished":       [0, 1, 3, 4, 6, 7, 9, 10],
}

NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
NOTE_TO_MIDI = {n: i + 12 for i, n in enumerate(NOTE_NAMES)}  # C0=12

# ============================================================
# ENUMS
# ============================================================

class InstrumentClass(str, Enum):
    """High-level instrument categorization for prompt engineering."""
    DRUMS = "drums"
    BASS = "bass"
    CHORDS = "chords"
    MELODY = "melody"
    PAD = "pad"
    FX = "fx"
    PERCUSSION = "percussion"
    VOCALS = "vocals"
    ARPEGGIO = "arpeggio"
    LEAD = "lead"

class PartRelation(str, Enum):
    """How this part relates to others in the project."""
    INTRO = "intro"
    VERSE = "verse"
    CHORUS = "chorus"
    BRIDGE = "bridge"
    DROP = "drop"
    BUILD = "build"
    FILL = "fill"
    OUTRO = "outro"
    TRANSITION = "transition"
    SOLO = "solo"

class TimeDivision(str, Enum):
    """Standard time signatures."""
    TWO_TWO = "2/2"
    THREE_FOUR = "3/4"
    FOUR_FOUR = "4/4"
    FIVE_FOUR = "5/4"
    SIX_EIGHT = "6/8"
    SEVEN_EIGHT = "7/8"
    TWELVE_EIGHT = "12/8"

class EffectType(str, Enum):
    """Effects that can be applied to a part."""
    REVERB = "reverb"
    DELAY = "delay"
    CHORUS = "chorus"
    DISTORTION = "distortion"
    COMPRESSION = "compression"
    EQ = "eq"
    PHASER = "phaser"
    FLANGER = "flanger"
    SIDECHAIN = "sidechain"
    FILTER = "filter"

# ============================================================
# INSTRUMENT PRESETS
# ============================================================

INSTRUMENT_PRESETS = {
    # Bass
    "808_bass": {
        "class": "bass",
        "description": "deep subby 808 bass, sustained, heavy low end",
        "register": "low",
        "default_bpm_range": (60, 160),
    },
    "sub_bass": {
        "class": "bass",
        "description": "clean sub bass, sine wave, minimal harmonics",
        "register": "sub",
        "default_bpm_range": (60, 140),
    },
    "pluck_bass": {
        "class": "bass",
        "description": "plucked electric bass guitar, attacky",
        "register": "low-mid",
        "default_bpm_range": (80, 180),
    },
    "synth_bass": {
        "class": "bass",
        "description": "analog synthesizer bass, resonant filter sweep",
        "register": "low",
        "default_bpm_range": (100, 160),
    },
    
    # Drums
    "kick": {
        "class": "drums",
        "description": "punchy kick drum, subby thump",
        "register": "sub-low",
        "default_bpm_range": (60, 200),
    },
    "snare": {
        "class": "drums",
        "description": "crisp snare drum with crack",
        "register": "mid",
        "default_bpm_range": (60, 200),
    },
    "hi_hat": {
        "class": "drums",
        "description": "tight hi-hat pattern, 8th and 16th notes",
        "register": "high",
        "default_bpm_range": (80, 200),
    },
    "drums_full": {
        "class": "drums",
        "description": "full drum kit with kick, snare, hi-hat, toms",
        "register": "full",
        "default_bpm_range": (60, 180),
    },
    "trap_drums": {
        "class": "drums",
        "description": "trap drums with 808 kicks, rapid hi-hat rolls, rimshots",
        "register": "full",
        "default_bpm_range": (130, 170),
    },
    "techno_drums": {
        "class": "drums",
        "description": "techno drums with four-on-the-floor kick, closed hi-hat, clap",
        "register": "full",
        "default_bpm_range": (120, 150),
    },
    "dnb_drums": {
        "class": "drums",
        "description": "drum and bass breaks, fast, intricate percussion",
        "register": "full",
        "default_bpm_range": (165, 180),
    },
    "percussion_loop": {
        "class": "percussion",
        "description": "shakers, tambourine, congas, bongos, world percussion",
        "register": "mid-high",
        "default_bpm_range": (80, 140),
    },
    
    # Chords / Keys
    "piano": {
        "class": "chords",
        "description": "acoustic grand piano chords, warm and rich",
        "register": "mid",
        "default_bpm_range": (60, 160),
    },
    "synth_pad": {
        "class": "pad",
        "description": "warm analog synth pad, sustained, evolving filter",
        "register": "mid",
        "default_bpm_range": (60, 140),
    },
    "organ": {
        "class": "chords",
        "description": "hammond organ chords, soulful, gospel influence",
        "register": "mid",
        "default_bpm_range": (60, 140),
    },
    "wurlitzer": {
        "class": "chords",
        "description": "wurlitzer electric piano, vintage, percussive",
        "register": "mid",
        "default_bpm_range": (60, 130),
    },
    
    # Melody / Lead
    "synth_lead": {
        "class": "lead",
        "description": "monophonic synth lead, piercing, expressive",
        "register": "high",
        "default_bpm_range": (80, 180),
    },
    "violin": {
        "class": "melody",
        "description": "orchestral violin, legato, emotional",
        "register": "high",
        "default_bpm_range": (60, 140),
    },
    "flute": {
        "class": "melody",
        "description": "flute melody, airy, bright",
        "register": "high",
        "default_bpm_range": (60, 140),
    },
    "guitar_melody": {
        "class": "melody",
        "description": "electric guitar lead, bluesy, expressive bends",
        "register": "mid",
        "default_bpm_range": (60, 160),
    },
    
    # Arpeggio
    "arp": {
        "class": "arpeggio",
        "description": "synthesizer arpeggio pattern, sequenced, rhythmic",
        "register": "mid-high",
        "default_bpm_range": (100, 170),
    },
    "pluck_arp": {
        "class": "arpeggio",
        "description": "plucked synth arpeggio, rhythmic, decorative",
        "register": "high",
        "default_bpm_range": (100, 160),
    },
    
    # FX / Texture
    "riser": {
        "class": "fx",
        "description": "rising sound effect, tension builder, sweep",
        "register": "full",
        "default_bpm_range": (60, 200),
    },
    "texture_pad": {
        "class": "pad",
        "description": "ambient texture pad, atmospheric, evolving",
        "register": "mid",
        "default_bpm_range": (40, 100),
    },
    "noise_sweep": {
        "class": "fx",
        "description": "white noise sweep, transitional effect",
        "register": "full",
        "default_bpm_range": (60, 200),
    },
}


# ============================================================
# DATA CLASSES
# ============================================================

@dataclass
class PartEffect:
    """An effect applied to a part."""
    type: EffectType
    amount: float = 0.5  # 0.0 to 1.0
    params: Dict[str, float] = field(default_factory=dict)


@dataclass
class DAWPart:
    """
    A single instrument part in the DAW project.
    
    This is the fundamental building block of a project.
    Each part represents one instrument playing for a
    specific number of measures with precise musical parameters.
    """
    # Musical parameters
    bpm: int = 120
    division: str = "4/4"
    root: str = "C"
    scale: str = "natural_minor"
    measures: int = 8
    
    # Instrument
    instrument: str = "synth_pad"
    instrument_class: str = "pad"
    
    # Arrangement
    relation: str = "verse"
    order: int = 0  # Position in project
    
    # Mixing
    volume: float = 0.8      # 0.0 to 1.0
    pan: float = 0.0         # -1.0 (left) to 1.0 (right)
    effects: List[PartEffect] = field(default_factory=list)
    
    # AI generation
    extra_prompt: str = ""
    temperature: float = 1.0
    top_k: int = 250
    cfg_coef: float = 3.0
    
    # Auto-generated
    id: str = ""
    timestamp: str = ""
    
    # Results (filled after generation)
    audio_path: str = ""
    duration: float = 0.0
    analysis: Dict = field(default_factory=dict)
    
    def __post_init__(self):
        if not self.id:
            self.id = f"{self.instrument}_{self.relation}_{datetime.now().strftime('%H%M%S')}"
        if not self.timestamp:
            self.timestamp = datetime.now().isoformat()
    
    @property
    def beats_per_measure(self) -> int:
        """Get beats per measure from division string."""
        parts = self.division.split("/")
        return int(parts[0])
    
    @property
    def total_beats(self) -> int:
        """Total beats for this part."""
        return self.measures * self.beats_per_measure
    
    @property
    def duration_seconds(self) -> float:
        """Calculate duration in seconds based on BPM and measures."""
        return (self.total_beats / self.bpm) * 60.0
    
    @property
    def scale_notes(self) -> List[str]:
        """Get note names in this part's scale."""
        root_idx = NOTE_NAMES.index(self.root)
        pattern = SCALE_PATTERNS.get(self.scale, SCALE_PATTERNS["natural_minor"])
        return [NOTE_NAMES[(root_idx + i) % 12] for i in pattern]
    
    def to_dict(self) -> Dict:
        """Serialize to dictionary."""
        d = asdict(self)
        d['effects'] = [asdict(e) for e in self.effects]
        return d
    
    def build_prompt(self) -> str:
        """
        Build a precise, musician-focused prompt for MusicGen.
        
        This is the key innovation - instead of a vague prompt,
        we build a detailed musical specification that tells
        MusicGen exactly what to generate.
        """
        instrument_info = INSTRUMENT_PRESETS.get(self.instrument, {})
        instr_desc = instrument_info.get("description", self.instrument)
        instr_class = instrument_info.get("class", self.instrument_class)
        register = instrument_info.get("register", "mid")
        
        # Get scale info
        scale_notes_str = ", ".join(self.scale_notes)
        
        # Build relational context
        context_descriptions = {
            "intro": "introduction, establishing the mood",
            "verse": "verse section, supporting the narrative",
            "chorus": "chorus section, energetic and memorable",
            "bridge": "bridge section, contrasting and emotional",
            "drop": "drop section, maximum energy",
            "build": "build up section, rising tension",
            "fill": "fill section, transitional",
            "outro": "outro section, fading out",
            "transition": "transition section, connecting parts",
            "solo": "solo section, featured instrument",
        }
        context = context_descriptions.get(self.relation, self.relation)
        
        # Build the prompt
        prompt_parts = [
            f"Generate a {instr_desc} part for music production.",
            f"Time signature: {self.division}.",
            f"Tempo: {self.bpm} BPM.",
            f"Length: {self.measures} bars ({self.duration_seconds:.1f} seconds).",
            f"Key: {self.root} {self.scale.replace('_', ' ')}.",
            f"Scale notes: {scale_notes_str}.",
            f"Section: {context}.",
            f"Instrument register: {register}.",
        ]
        
        if self.extra_prompt:
            prompt_parts.append(f"Style: {self.extra_prompt}.")
        
        return " ".join(prompt_parts)
    
    def validate(self) -> List[str]:
        """Validate part parameters, return list of warnings."""
        warnings = []
        
        if self.bpm < 30 or self.bpm > 300:
            warnings.append(f"Unusual BPM: {self.bpm}")
        
        if self.root not in NOTE_NAMES:
            warnings.append(f"Invalid root note: {self.root}")
        
        if self.scale not in SCALE_PATTERNS:
            warnings.append(f"Unknown scale: {self.scale}")
        
        if self.measures < 1:
            warnings.append(f"Measures must be >= 1, got {self.measures}")
        
        if self.volume < 0.0 or self.volume > 1.0:
            warnings.append(f"Volume must be 0-1, got {self.volume}")
        
        if self.pan < -1.0 or self.pan > 1.0:
            warnings.append(f"Pan must be -1 to 1, got {self.pan}")
        
        return warnings


@dataclass
class DAWProject:
    """
    A complete music production project.
    
    Manages multiple DAWPart instances with:
    - Project-level key/scale (all parts inherit by default)
    - Mixing (volume, pan per part)
    - Timeline (order of parts)
    - Project file save/load
    """
    name: str = "Untitled"
    bpm: int = 120
    division: str = "4/4"
    root: str = "C"
    scale: str = "natural_minor"
    parts: List[DAWPart] = field(default_factory=list)
    created: str = ""
    modified: str = ""
    project_dir: str = ""
    
    def __post_init__(self):
        now = datetime.now()
        if not self.created:
            self.created = now.isoformat()
        self.modified = now.isoformat()
    
    def add_part(self, part: DAWPart) -> int:
        """
        Add a part to the project.
        Returns the index of the added part.
        """
        # Inherit project defaults if not specified
        if part.bpm == 120 and self.bpm != 120:
            part.bpm = self.bpm
        if part.division == "4/4" and self.division != "4/4":
            part.division = self.division
        if part.root == "C" and self.root != "C":
            part.root = self.root
        if part.scale == "natural_minor" and self.scale != "natural_minor":
            part.scale = self.scale
        
        part.order = len(self.parts)
        self.parts.append(part)
        self.modified = datetime.now().isoformat()
        return len(self.parts) - 1
    
    def remove_part(self, index: int) -> Optional[DAWPart]:
        """Remove a part by index."""
        if 0 <= index < len(self.parts):
            part = self.parts.pop(index)
            # Re-index remaining parts
            for i, p in enumerate(self.parts):
                p.order = i
            self.modified = datetime.now().isoformat()
            return part
        return None
    
    def get_part(self, index: int) -> Optional[DAWPart]:
        """Get a part by index."""
        if 0 <= index < len(self.parts):
            return self.parts[index]
        return None
    
    @property
    def total_duration(self) -> float:
        """Calculate total duration of all parts (worst case)."""
        max_end = 0
        for part in self.parts:
            end = (part.order + 1) * part.duration_seconds
            max_end = max(max_end, end)
        return max_end
    
    def save(self, filepath: str):
        """Save project to JSON file."""
        data = {
            'project': {
                'name': self.name,
                'bpm': self.bpm,
                'division': self.division,
                'root': self.root,
                'scale': self.scale,
                'created': self.created,
                'modified': datetime.now().isoformat(),
            },
            'parts': [p.to_dict() for p in self.parts],
        }
        
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2, default=str)
        
        self.modified = datetime.now().isoformat()
        print(f"Project saved: {filepath}")
    
    @classmethod
    def load(cls, filepath: str) -> 'DAWProject':
        """Load project from JSON file."""
        with open(filepath, 'r') as f:
            data = json.load(f)
        
        proj_data = data.get('project', {})
        project = cls(
            name=proj_data.get('name', 'Untitled'),
            bpm=proj_data.get('bpm', 120),
            division=proj_data.get('division', '4/4'),
            root=proj_data.get('root', 'C'),
            scale=proj_data.get('scale', 'natural_minor'),
            created=proj_data.get('created', ''),
            project_dir=os.path.dirname(filepath),
        )
        
        for part_data in data.get('parts', []):
            effects = []
            for ef in part_data.pop('effects', []):
                effects.append(PartEffect(
                    type=EffectType(ef['type']),
                    amount=ef.get('amount', 0.5),
                    params=ef.get('params', {}),
                ))
            part_data['effects'] = effects
            project.parts.append(DAWPart(**part_data))
        
        print(f"Project loaded: {filepath}")
        print(f"  Parts: {len(project.parts)}")
        print(f"  BPM: {project.bpm}, Key: {project.root} {project.scale}")
        return project


# ============================================================
# MEMORY SYSTEM
# ============================================================

class DAWMemory:
    """
    Project memory that tracks generation context for coherence.
    
    Stores what was generated before so that new parts can
    build on existing musical ideas.
    """
    
    def __init__(self):
        self.history: List[Dict] = []
        self.themes: Dict[str, List] = {}  # relation -> [generated info]
        self.active_keys: Dict[str, int] = {}  # track usage counts
    
    def record_part(self, part: DAWPart, audio_path: str, analysis: Dict):
        """Record a generated part in memory."""
        record = {
            'instrument': part.instrument,
            'relation': part.relation,
            'root': part.root,
            'scale': part.scale,
            'bpm': part.bpm,
            'measures': part.measures,
            'audio_path': audio_path,
            'analysis': analysis,
            'timestamp': datetime.now().isoformat(),
        }
        self.history.append(record)
        
        # Track by relation
        if part.relation not in self.themes:
            self.themes[part.relation] = []
        self.themes[part.relation].append(record)
        
        # Count instrument usage
        key = f"{part.instrument}_{part.relation}"
        self.active_keys[key] = self.active_keys.get(key, 0) + 1
    
    def get_context_for(self, part: DAWPart) -> str:
        """
        Build contextual description from memory for a new part.
        
        Tells MusicGen what already exists so it can blend in.
        """
        if not self.history:
            return ""
        
        context_parts = []
        
        # What's already playing in the project
        existing_instruments = set()
        for record in self.history:
            existing_instruments.add(record['instrument'])
        
        if existing_instruments:
            context_parts.append(
                f"Existing instruments: {', '.join(existing_instruments)}."
            )
        
        # Previous part in the same section
        same_relation = self.themes.get(part.relation, [])
        if same_relation:
            prev = same_relation[-1]
            context_parts.append(
                f"Previous {part.relation} had {prev['instrument']} "
                f"in {prev['root']} {prev['scale']} at {prev['bpm']} BPM."
            )
        
        # Overall project progress
        context_parts.append(
            f"This is part {len(self.history) + 1} in the project."
        )
        
        return " ".join(context_parts)
    
    def summary(self) -> str:
        """Get a summary of what's been generated."""
        lines = []
        lines.append(f"Total parts: {len(self.history)}")
        lines.append(f"Sections: {', '.join(self.themes.keys())}")
        for relation, records in self.themes.items():
            instrs = [r['instrument'] for r in records]
            lines.append(f"  {relation}: {', '.join(instrs)}")
        return "\n".join(lines)


# ============================================================
# PART GENERATOR
# ============================================================

class DAWPartGenerator:
    """
    Generates audio for a single DAWPart using MusicGen.
    
    Key features:
    - Builds precise prompts from musical parameters
    - Maintains memory for project coherence
    - Extracts audio analysis (tempo, beats, keys)
    - Validates generated audio against specifications
    """
    
    def __init__(self, model_size: str = 'small'):
        self.musicgen = MusicGenGenerator(model_size=model_size)
        self.analyzer = AudioAnalyzer() if MUSICGEN_AVAILABLE else None
        self.memory = DAWMemory()
        self.generation_count = 0
        
        print(f"\n{'='*60}")
        print("DAW Part Generator Status:")
        print(f"  MusicGen: {'READY' if self.musicgen.available else 'NOT INSTALLED'}")
        print(f"  Audio Analysis: {'READY' if (self.analyzer and self.analyzer.available) else 'NOT AVAILABLE'}")
        print(f"{'='*60}\n")
    
    def generate_part(self, part: DAWPart, output_dir: str = "output") -> Dict:
        """
        Generate audio for a single part.
        
        Args:
            part: The DAWPart to generate
            output_dir: Where to save the audio file
        
        Returns:
            Dict with keys: 'audio', 'analysis', 'path', 'success'
        """
        result = {
            'audio': None,
            'analysis': {},
            'path': '',
            'success': False,
            'warnings': [],
        }
        
        # Validate
        warnings = part.validate()
        if warnings:
            result['warnings'] = warnings
            for w in warnings:
                print(f"  Warning: {w}")
        
        if not self.musicgen.available:
            print("MusicGen not available. Install transformers and torchaudio.")
            return result
        
        # Build prompt with context from memory
        prompt = part.build_prompt()
        context = self.memory.get_context_for(part)
        if context:
            full_prompt = f"{prompt} {context}"
        else:
            full_prompt = prompt
        
        print(f"\n{'='*50}")
        print(f"Generating Part: {part.id}")
        print(f"  Instrument: {part.instrument}")
        print(f"  BPM: {part.bpm} | Division: {part.division}")
        print(f"  Key: {part.root} {part.scale}")
        print(f"  Measures: {part.measures} ({part.duration_seconds:.1f}s)")
        print(f"  Relation: {part.relation}")
        print(f"  Pitch/Temperature: {part.temperature}")
        print(f"  Prompt: {prompt}")
        if context:
            print(f"  Context: {context}")
        print(f"{'='*50}")
        
        # Generate audio
        audio = self.musicgen.generate(
            prompt=full_prompt,
            duration=int(part.duration_seconds) + 1,  # Add 1s buffer
            temperature=part.temperature,
            top_k=part.top_k,
            cfg_coef=part.cfg_coef,
        )
        
        if audio is None:
            print("Generation failed.")
            return result
        
        # Trim to exact duration
        expected_samples = int(part.duration_seconds * 32000)
        if audio.shape[-1] > expected_samples:
            if audio.ndim == 2:
                audio = audio[:, :expected_samples]
            else:
                audio = audio[:expected_samples]
        
        result['audio'] = audio
        
        # Analyze
        if self.analyzer and self.analyzer.available:
            result['analysis'] = self.analyzer.analyze(audio)
            part.analysis = result['analysis']
            
            # Check if tempo matches
            if 'tempo' in result['analysis']:
                detected_bpm = result['analysis']['tempo']
                ratio = detected_bpm / part.bpm
                if ratio < 0.5 or ratio > 2.0:
                    result['warnings'].append(
                        f"Detected tempo ({detected_bpm:.0f} BPM) differs significantly "
                        f"from requested ({part.bpm} BPM). Consider adjusting."
                    )
        
        # Save audio
        part.audio_path = self._save_audio(audio, part, output_dir)
        result['path'] = part.audio_path
        part.duration = audio.shape[-1] / 32000
        
        # Record in memory
        self.memory.record_part(part, part.audio_path, result['analysis'])
        self.generation_count += 1
        
        result['success'] = True
        print(f"\n✓ Part generated: {part.audio_path}")
        print(f"  Duration: {part.duration:.1f}s")
        
        return result
    
    def _save_audio(self, audio: np.ndarray, part: DAWPart, output_dir: str) -> str:
        """Save generated audio to file."""
        os.makedirs(output_dir, exist_ok=True)
        
        filename = f"{part.id}_{datetime.now().strftime('%H%M%S')}.wav"
        filepath = os.path.join(output_dir, filename)
        
        if audio.ndim == 2:
            audio_for_sf = audio.T if audio.shape[0] <= 2 else audio
        else:
            audio_for_sf = audio
        
        sf.write(filepath, audio_for_sf, 32000)
        return filepath
    
    def generate_replacement(self, part_index: int, new_part: DAWPart, 
                            output_dir: str = "output") -> Dict:
        """
        Generate a replacement for an existing part.
        Removes old part from memory and generates new one.
        """
        # Since we can't easily remove from memory history,
        # we just generate the new part with context of everything else
        return self.generate_part(new_part, output_dir)
    
    def validate_project_coherence(self, project: DAWProject) -> List[str]:
        """Check if all parts in a project are musically coherent."""
        issues = []
        
        if not project.parts:
            return issues
        
        # Check key consistency
        roots = set(p.root for p in project.parts)
        if len(roots) > 1:
            issues.append(f"Multiple keys detected: {roots}")
        
        # Check BPM consistency
        bpms = set(p.bpm for p in project.parts)
        if len(bpms) > 1:
            issues.append(f"Multiple BPMs detected: {bpms}. Ensure they match.")
        
        return issues


# ============================================================
# MIXING ENGINE
# ============================================================

class DAWMixer:
    """
    Simple mixer for combining multiple parts into a final mix.
    
    Mixes parts with volume, pan, and crossfade between sections.
    """
    
    def __init__(self, sample_rate: int = 32000):
        self.sample_rate = sample_rate
    
    def mix_project(self, project: DAWProject, output_dir: str = "output") -> str:
        """
        Mix all parts in a project into a single WAV file.
        
        Aligns parts by their order, creating a timeline.
        """
        if not project.parts:
            print("No parts to mix.")
            return ""
        
        # Calculate total timeline length
        timeline_end = 0
        current_time = 0
        timeline: List[Tuple[int, DAWPart, float]] = []  # (sample_start, part, volume)
        
        for i, part in enumerate(project.parts):
            if not part.audio_path or not os.path.exists(part.audio_path):
                print(f"Part {i} ({part.id}) has no audio, skipping.")
                continue
            
            # Read audio
            audio, sr = sf.read(part.audio_path)
            if sr != self.sample_rate:
                # Resample (simplified)
                pass
            
            # Ensure stereo
            if audio.ndim == 1:
                audio = np.column_stack([audio, audio])
            
            # Apply volume and pan
            left_gain = part.volume * (1.0 - max(0, part.pan))
            right_gain = part.volume * (1.0 - max(0, -part.pan))
            audio[:, 0] *= left_gain
            audio[:, 1] *= right_gain
            
            # Align to timeline
            start_sample = int(current_time * self.sample_rate)
            timeline.append((start_sample, audio))
            
            current_time += part.duration_seconds
            timeline_end = max(timeline_end, start_sample + audio.shape[0])
        
        if not timeline:
            return ""
        
        # Create master mix
        master = np.zeros((timeline_end, 2), dtype=np.float32)
        
        for start_sample, audio_data in timeline:
            end = min(start_sample + audio_data.shape[0], timeline_end)
            span = end - start_sample
            master[start_sample:end] += audio_data[:span]
        
        # Normalize
        max_val = np.max(np.abs(master))
        if max_val > 1.0:
            master /= max_val
        
        # Save
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, f"{project.name}_mix.wav")
        sf.write(output_path, master, self.sample_rate)
        print(f"Mix saved: {output_path}")
        print(f"  Duration: {timeline_end / self.sample_rate:.1f}s")
        print(f"  Parts: {len(timeline)}")
        
        return output_path


# ============================================================
# PRESET BUILDERS
# ============================================================

def create_intro_part(bpm: int = 100, root: str = "C", scale: str = "major") -> DAWPart:
    """Create a typical intro part."""
    return DAWPart(
        bpm=bpm, root=root, scale=scale,
        instrument="texture_pad", instrument_class="pad",
        measures=4, relation="intro",
        volume=0.5, temperature=0.8,
        extra_prompt="atmospheric, building anticipation, sparse",
    )

def create_drum_part(bpm: int = 140, style: str = "trap_drums", measures: int = 8) -> DAWPart:
    """Create a drum part."""
    return DAWPart(
        bpm=bpm, root="C", scale="chromatic",
        instrument=style, instrument_class="drums",
        measures=measures, relation="verse",
        volume=0.9, temperature=0.7,
        extra_prompt="consistent groove, good energy",
    )

def create_bass_part(bpm: int = 140, root: str = "C", scale: str = "natural_minor",
                     style: str = "808_bass", measures: int = 8) -> DAWPart:
    """Create a bass part following the key."""
    return DAWPart(
        bpm=bpm, root=root, scale=scale,
        instrument=style, instrument_class="bass",
        measures=measures, relation="verse",
        volume=0.8, temperature=0.6,
        extra_prompt=f"follow {root} {scale} scale, solid root notes",
    )

def create_chord_part(bpm: int = 140, root: str = "C", scale: str = "natural_minor",
                      style: str = "synth_pad", measures: int = 8) -> DAWPart:
    """Create a chord/pad part."""
    return DAWPart(
        bpm=bpm, root=root, scale=scale,
        instrument=style, instrument_class="pad",
        measures=measures, relation="chorus",
        volume=0.6, temperature=0.9,
        extra_prompt=f"warm chords in {root} {scale}, sustained",
    )

def create_melody_part(bpm: int = 140, root: str = "C", scale: str = "natural_minor",
                       style: str = "synth_lead", measures: int = 8) -> DAWPart:
    """Create a melody/lead part."""
    return DAWPart(
        bpm=bpm, root=root, scale=scale,
        instrument=style, instrument_class="lead",
        measures=measures, relation="chorus",
        volume=0.7, temperature=1.2,  # Higher temp for more creative melodies
        extra_prompt=f"catchy melody in {root} {scale}, expressive",
    )


if __name__ == "__main__":
    # Demonstration
    print("DAW Engine Demo")
    print("="*50)
    
    # Create a project
    project = DAWProject(
        name="Demo Track",
        bpm=140,
        root="C",
        scale="natural_minor",
    )
    
    # Add some parts
    project.add_part(create_intro_part(bpm=140))
    project.add_part(create_drum_part(bpm=140))
    project.add_part(create_bass_part(bpm=140))
    project.add_part(create_chord_part(bpm=140))
    project.add_part(create_melody_part(bpm=140))
    
    print(f"\nProject: {project.name}")
    print(f"Parts: {len(project.parts)}")
    for i, p in enumerate(project.parts):
        print(f"  [{i}] {p.instrument:20s} | {p.relation:10s} | {p.measures} bars @ {p.bpm} BPM")
    
    print(f"\nTotal duration (approx): {project.total_duration:.1f}s")
    
    # Save project
    project.save("output/demo_project.json")
    
    # Load it back
    loaded = DAWProject.load("output/demo_project.json")
    print(f"\nLoaded project: {loaded.name}")
    print(f"Parts: {len(loaded.parts)}")