"""
Studio Onyrix v4 - AI-Powered DAW Music Production System

Generate individual instrument parts with precise musical control.
Think of it as a DAW where each track is generated by AI.

Usage:
  # Interactive mode (recommended)
  python main.py
  
  # Add a single part
  python main.py part --instrument 808_bass --bpm 140 --root C --scale natural_minor --measures 8
  
  # Generate from preset
  python main.py part --preset bass --bpm 140 --root C --scale natural_minor
  
  # Mix project
  python main.py mix
  
  # List project parts
  python main.py list
  
  # Remove a part
  python main.py remove 0
  
  # Load/save projects
  python main.py save my_song.json
  python main.py load my_song.json
  python main.py new
  
  # List available instruments
  python main.py instruments
"""

import sys
import os
import json

# Import DAW engine
from daw_engine import (
    DAWProject, DAWPart, DAWPartGenerator, DAWMixer,
    INSTRUMENT_PRESETS, SCALE_PATTERNS, NOTE_NAMES,
    create_intro_part, create_drum_part, create_bass_part,
    create_chord_part, create_melody_part,
    InstrumentClass, PartRelation, TimeDivision,
)


# ============================================================
# PROJECT STATE
# ============================================================

CURRENT_PROJECT = DAWProject(name="Untitled", bpm=120, root="C", scale="natural_minor")
PROJECT_FILE = "output/project.json"
GENERATOR = None  # Lazy initialized


def get_generator() -> DAWPartGenerator:
    """Get or initialize the DAW part generator."""
    global GENERATOR
    if GENERATOR is None:
        print("Initializing DAW Part Generator...")
        GENERATOR = DAWPartGenerator(model_size='small')
    return GENERATOR


def ensure_project_loaded():
    """Load project if exists."""
    global CURRENT_PROJECT
    if os.path.exists(PROJECT_FILE):
        try:
            CURRENT_PROJECT = DAWProject.load(PROJECT_FILE)
            print(f"Loaded project: {CURRENT_PROJECT.name}")
        except Exception:
            CURRENT_PROJECT = DAWProject(name="Untitled", bpm=120, root="C", scale="natural_minor")


def save_project():
    """Save current project to default location."""
    os.makedirs("output", exist_ok=True)
    CURRENT_PROJECT.save(PROJECT_FILE)


# ============================================================
# COMMAND HANDLERS
# ============================================================

def cmd_new_project(args):
    """Create a new project."""
    global CURRENT_PROJECT
    kwargs = parse_flags(args)
    positional = [a for a in args if not a.startswith("--")]
    name = kwargs.get("name") or (positional[0] if positional else input("Project name: ").strip() or "Untitled")
    CURRENT_PROJECT = DAWProject(
        name=name,
        bpm=int(kwargs.get("bpm", 120)),
        division=kwargs.get("division", "4/4"),
        root=kwargs.get("root", "C"),
        scale=kwargs.get("scale", "natural_minor"),
    )
    print(f"New project created: {name}")


def parse_flags(args):
    """Parse simple --key value flags used by the CLI and interactive shell."""
    kwargs = {}
    i = 0
    while i < len(args):
        if args[i].startswith("--"):
            key = args[i][2:]
            if i + 1 < len(args) and not args[i + 1].startswith("--"):
                value = args[i + 1]
                i += 2
            else:
                value = True
                i += 1
            kwargs[key] = value
        else:
            i += 1
    return kwargs


def cmd_add_part(args):
    """
    Add and generate a part.
    
    Usage: python main.py part --instrument 808_bass --bpm 140 --root C ...
    """
    kwargs = parse_flags(args)
    
    # Map to DAWPart fields
    # Musical
    bpm = int(kwargs.get('bpm', 120))
    division = kwargs.get('division', '4/4')
    root = kwargs.get('root', CURRENT_PROJECT.root)
    scale = kwargs.get('scale', CURRENT_PROJECT.scale)
    measures = int(kwargs.get('measures', 8))
    
    # Instrument
    instrument = kwargs.get('instrument', kwargs.get('preset', 'synth_pad'))
    instr_info = INSTRUMENT_PRESETS.get(instrument, {})
    instrument_class = instr_info.get('class', 'pad')
    relation = kwargs.get('relation', 'verse')
    volume = float(kwargs.get('volume', 0.8))
    pan = float(kwargs.get('pan', 0.0))
    start_bar = float(kwargs.get('start', kwargs.get('bar', 1.0)))
    temperature = float(kwargs.get('temperature', 1.0))
    
    # If preset, load from presets
    if kwargs.get('preset'):
        preset_name = kwargs['preset']
        preset_map = {
            'intro': ('texture_pad', 'pad', 0.5, 0.8, 'intro'),
            'drums': ('trap_drums', 'drums', 0.9, 0.7, 'verse'),
            'bass': ('808_bass', 'bass', 0.8, 0.6, 'verse'),
            'chords': ('synth_pad', 'pad', 0.6, 0.9, 'chorus'),
            'melody': ('synth_lead', 'lead', 0.7, 1.2, 'chorus'),
            'kick': ('kick', 'drums', 0.9, 0.5, 'verse'),
            'hihat': ('hi_hat', 'drums', 0.7, 0.5, 'verse'),
            'arp': ('pluck_arp', 'arpeggio', 0.6, 0.8, 'verse'),
            'fx_riser': ('riser', 'fx', 0.5, 0.9, 'transition'),
        }
        if preset_name in preset_map:
            instr, iclass, vol, temp, rel = preset_map[preset_name]
            instrument = instr
            instrument_class = iclass
            relation = kwargs.get('relation', rel)
            volume = float(kwargs.get('volume', vol))
            temperature = float(kwargs.get('temperature', temp))
    
    # Get instrument info
    instr_info = INSTRUMENT_PRESETS.get(instrument, {})
    instrument_class = kwargs.get('class', instrument_class or instr_info.get('class', 'pad'))
    
    # Arrangement and project-level musical constraints
    track_id = kwargs.get('track', '')
    if kwargs.get('chords'):
        CURRENT_PROJECT.chord_progression = [
            c.strip() for c in kwargs['chords'].replace(",", " ").split() if c.strip()
        ]
    if kwargs.get('groove'):
        CURRENT_PROJECT.groove = kwargs['groove']
    if kwargs.get('swing'):
        CURRENT_PROJECT.swing = float(kwargs['swing'])
    
    # AI params
    extra_prompt = kwargs.get('prompt', kwargs.get('extra', ''))
    top_k = int(kwargs.get('top_k', 250))
    cfg_coef = float(kwargs.get('cfg', 3.0))
    
    # Create part
    part = DAWPart(
        bpm=bpm,
        division=division,
        root=root,
        scale=scale,
        measures=measures,
        instrument=instrument,
        instrument_class=instrument_class,
        relation=relation,
        track_id=track_id,
        start_bar=start_bar,
        volume=volume,
        pan=pan,
        extra_prompt=extra_prompt,
        temperature=temperature,
        top_k=top_k,
        cfg_coef=cfg_coef,
    )
    
    # Add to project
    index = CURRENT_PROJECT.add_part(part)
    save_project()
    
    print(f"\nPart [{index}] added to project: {part.instrument} ({part.relation})")
    print(f"  BPM: {part.bpm} | Division: {part.division}")
    print(f"  Key: {part.root} {part.scale} | Measures: {part.measures}")
    print(f"  Track: {part.track_id} | Start bar: {part.start_bar:g} | End bar: {part.end_bar:g}")
    print(f"  Duration: {part.duration_seconds:.1f}s | Volume: {part.volume} | Pan: {part.pan}")
    if part.extra_prompt:
        print(f"  Extra: {part.extra_prompt}")
    
    # Ask to generate
    gen_prompt = kwargs.get('generate', kwargs.get('gen', 'true'))
    should_generate = gen_prompt.lower() in ('true', 'yes', 'y', '1')
    
    if should_generate:
        print(f"\nGenerating part...")
        generator = get_generator()
        if generator.musicgen.available:
            result = generator.generate_part(part, project=CURRENT_PROJECT)
            if result['success']:
                print(f"  Audio: {result['path']}")
                if result['analysis']:
                    if 'tempo' in result['analysis']:
                        print(f"  Detected tempo: {result['analysis']['tempo']:.0f} BPM")
            save_project()
        else:
            print("MusicGen not available. Install transformers torchaudio.")


def cmd_list_parts(args):
    """List all parts in the current project."""
    print(f"\n{'='*60}")
    print(f"Project: {CURRENT_PROJECT.name}")
    print(f"BPM: {CURRENT_PROJECT.bpm} | Key: {CURRENT_PROJECT.root} {CURRENT_PROJECT.scale}")
    print(f"Division: {CURRENT_PROJECT.division}")
    if CURRENT_PROJECT.chord_progression:
        print(f"Chords: {' - '.join(CURRENT_PROJECT.chord_progression)}")
    print(f"Groove: {CURRENT_PROJECT.groove} | Swing: {CURRENT_PROJECT.swing:.0%}")
    print(f"{'='*60}")
    
    if not CURRENT_PROJECT.parts:
        print("No parts in project.")
        return
    
    print(f"\n{'#':<3} {'Track':<10} {'Instrument':<18} {'Section':<10} {'Start':<6} {'End':<6} {'Bars':<5} {'Audio':<24}")
    print(f"{'-'*90}")
    
    for i, part in enumerate(CURRENT_PROJECT.parts):
        has_audio = "✓" if part.audio_path and os.path.exists(part.audio_path) else "✗"
        audio_file = os.path.basename(part.audio_path) if part.audio_path else ""
        print(f"{i:<3} {part.track_id:<10} {part.instrument:<18} {part.relation:<10} {part.start_bar:<6g} {part.end_bar:<6g} {part.measures:<5} {has_audio} {audio_file:<24}")
    
    print(f"\nTotal: {len(CURRENT_PROJECT.parts)} parts")


def cmd_remove_part(args):
    """Remove a part by index."""
    if not args:
        print("Usage: main.py remove <index>")
        return
    
    try:
        index = int(args[0])
        part = CURRENT_PROJECT.remove_part(index)
        if part:
            print(f"Removed part [{index}]: {part.instrument} ({part.relation})")
            save_project()
        else:
            print(f"No part at index {index}")
    except ValueError:
        print(f"Invalid index: {args[0]}")


def cmd_mix(args):
    """Mix all parts into a final audio file."""
    if not CURRENT_PROJECT.parts:
        print("No parts to mix.")
        return
    
    # Check all parts have audio
    missing = [i for i, p in enumerate(CURRENT_PROJECT.parts) 
               if not p.audio_path or not os.path.exists(p.audio_path)]
    if missing:
        print(f"Parts missing audio: {missing}")
        print("Generate missing parts first, or use --force to mix available parts.")
        if '--force' not in args:
            return
    
    mixer = DAWMixer()
    output = mixer.mix_project(CURRENT_PROJECT)
    if output:
        print(f"\nFinal mix saved: {output}")
        # Get total duration from file
        try:
            import soundfile as sf
            audio, sr = sf.read(output)
            print(f"Duration: {len(audio) / sr:.1f}s")
            print(f"Sample rate: {sr} Hz")
        except ImportError:
            pass


def cmd_instruments(args):
    """List all available instruments."""
    print(f"\n{'='*60}")
    print("Available Instruments")
    print(f"{'='*60}")
    
    # Group by class
    by_class = {}
    for name, info in INSTRUMENT_PRESETS.items():
        iclass = info.get('class', 'other')
        if iclass not in by_class:
            by_class[iclass] = []
        by_class[iclass].append((name, info))
    
    for iclass, instruments in by_class.items():
        print(f"\n[{iclass.upper()}]")
        for name, info in instruments:
            bpm_range = info.get('default_bpm_range', (0, 0))
            print(f"  {name:<20s} {info['description']:<50s} {bpm_range[0]:>3}-{bpm_range[1]:>3} BPM")


def cmd_scales(args):
    """List all available scales."""
    print(f"\n{'='*60}")
    print("Available Scales")
    print(f"{'='*60}")
    for name, pattern in sorted(SCALE_PATTERNS.items()):
        notes = ", ".join(NOTE_NAMES[i % 12] for i in pattern)
        print(f"  {name:<20s} [{notes}]")


def cmd_tracks(args):
    """List mixer/timeline tracks."""
    print(f"\n{'='*60}")
    print("Tracks")
    print(f"{'='*60}")
    print(f"{'ID':<12} {'Name':<16} {'Class':<12} {'Vol':<6} {'Pan':<6} {'State':<10}")
    print(f"{'-'*70}")
    for track in CURRENT_PROJECT.tracks:
        state = "solo" if track.solo else ("muted" if track.muted else "active")
        print(f"{track.id:<12} {track.name:<16} {track.instrument_class:<12} {track.volume:<6.2f} {track.pan:<6.2f} {state:<10}")


def cmd_arrangement(args):
    """Set project-wide musical constraints for future generated parts."""
    kwargs = parse_flags(args)
    if kwargs.get('chords'):
        CURRENT_PROJECT.chord_progression = [
            c.strip() for c in kwargs['chords'].replace(",", " ").split() if c.strip()
        ]
    if kwargs.get('groove'):
        CURRENT_PROJECT.groove = kwargs['groove']
    if kwargs.get('swing'):
        CURRENT_PROJECT.swing = float(kwargs['swing'])
    if kwargs.get('bpm'):
        CURRENT_PROJECT.bpm = int(kwargs['bpm'])
    if kwargs.get('root'):
        CURRENT_PROJECT.root = kwargs['root']
    if kwargs.get('scale'):
        CURRENT_PROJECT.scale = kwargs['scale']
    save_project()
    print("Arrangement updated.")
    print(f"  BPM: {CURRENT_PROJECT.bpm}")
    print(f"  Key: {CURRENT_PROJECT.root} {CURRENT_PROJECT.scale}")
    print(f"  Chords: {' - '.join(CURRENT_PROJECT.chord_progression) if CURRENT_PROJECT.chord_progression else '-'}")
    print(f"  Groove: {CURRENT_PROJECT.groove} | Swing: {CURRENT_PROJECT.swing:.0%}")


def cmd_save(args):
    """Save project to file."""
    filepath = args[0] if args else PROJECT_FILE
    os.makedirs("output", exist_ok=True)
    if not filepath.startswith("output"):
        filepath = os.path.join("output", filepath)
    CURRENT_PROJECT.save(filepath)


def cmd_load(args):
    """Load project from file."""
    global CURRENT_PROJECT
    if not args:
        print("Usage: main.py load <filepath>")
        return
    filepath = args[0]
    if not os.path.exists(filepath):
        filepath = os.path.join("output", filepath)
    if os.path.exists(filepath):
        CURRENT_PROJECT = DAWProject.load(filepath)
    else:
        print(f"File not found: {filepath}")


def cmd_generate_all(args):
    """Generate all parts that don't have audio yet."""
    generator = get_generator()
    if not generator.musicgen.available:
        print("MusicGen not available.")
        return
    
    for i, part in enumerate(CURRENT_PROJECT.parts):
        if part.audio_path and os.path.exists(part.audio_path):
            print(f"  [{i}] Already generated, skipping: {part.instrument}")
            continue
        
        print(f"\n  [{i}] Generating: {part.instrument} ({part.relation})...")
        result = generator.generate_part(part, project=CURRENT_PROJECT)
        if result['success']:
            print(f"    ✓ Audio saved")
        else:
            print(f"    ✗ Failed")
    
    save_project()


def cmd_show(args):
    """Show project summary."""
    print(f"\n{'='*60}")
    print(f"Studio Onyrix - Project Summary")
    print(f"{'='*60}")
    print(f"Name: {CURRENT_PROJECT.name}")
    print(f"BPM: {CURRENT_PROJECT.bpm}")
    print(f"Division: {CURRENT_PROJECT.division}")
    print(f"Key: {CURRENT_PROJECT.root} {CURRENT_PROJECT.scale}")
    print(f"Chords: {' - '.join(CURRENT_PROJECT.chord_progression) if CURRENT_PROJECT.chord_progression else '-'}")
    print(f"Groove: {CURRENT_PROJECT.groove} | Swing: {CURRENT_PROJECT.swing:.0%}")
    print(f"Tracks: {len(CURRENT_PROJECT.tracks)}")
    print(f"Parts: {len(CURRENT_PROJECT.parts)}")
    
    if CURRENT_PROJECT.parts:
        # Breakdown by section
        sections = {}
        for p in CURRENT_PROJECT.parts:
            sections.setdefault(p.relation, []).append(p.instrument)
        
        print(f"\nArrangement:")
        for rel, instrs in sections.items():
            print(f"  {rel}: {', '.join(instrs)}")
        
        # Total duration
        total = CURRENT_PROJECT.total_duration
        print(f"\nEstimated duration: {total:.1f}s ({total/60:.1f} min)")


def cmd_info(args):
    """Show information about a specific parts."""
    if not args:
        print("Usage: main.py info <index>")
        return
    try:
        index = int(args[0])
        part = CURRENT_PROJECT.get_part(index)
        if not part:
            print(f"No part at index {index}")
            return
        
        print(f"\n{'='*50}")
        print(f"Part [{index}]: {part.instrument}")
        print(f"{'='*50}")
        print(f"  ID: {part.id}")
        print(f"  Class: {part.instrument_class}")
        print(f"  Relation: {part.relation}")
        print(f"  Track: {part.track_id}")
        print(f"  Start bar: {part.start_bar:g}")
        print(f"  End bar: {part.end_bar:g}")
        print(f"  BPM: {part.bpm}")
        print(f"  Division: {part.division}")
        print(f"  Key: {part.root} {part.scale}")
        print(f"  Measures: {part.measures}")
        print(f"  Duration: {part.duration:.1f}s / {part.duration_seconds:.1f}s (calc)")
        print(f"  Volume: {part.volume}")
        print(f"  Pan: {part.pan}")
        print(f"  Temperature: {part.temperature}")
        print(f"  Extra Prompt: {part.extra_prompt or '-'}")
        print(f"  Audio: {part.audio_path or '-'}")
        if part.analysis:
            print(f"  Analysis:")
            for k, v in part.analysis.items():
                if isinstance(v, float):
                    print(f"    {k}: {v:.2f}")
                elif isinstance(v, list) and len(v) > 5:
                    print(f"    {k}: [{v[0]:.1f}, {v[1]:.1f}, ...] ({len(v)} values)")
                else:
                    print(f"    {k}: {v}")
        print(f"  Prompt: {part.build_prompt()}")
        
    except ValueError:
        print(f"Invalid index: {args[0]}")


def cmd_interactive(args):
    """Enter interactive mode."""
    print(f"\n{'='*60}")
    print("Studio Onyrix - Interactive Mode")
    print(f"{'='*60}")
    print("Type 'help' for commands, 'exit' to quit.")
    
    while True:
        try:
            cmd = input(f"\n[{CURRENT_PROJECT.name}] > ").strip()
            if not cmd:
                continue
            
            parts = cmd.split()
            command = parts[0]
            cmd_args = parts[1:]
            
            if command in ('exit', 'quit', 'q'):
                save_project()
                print("Project saved. Goodbye!")
                break
            
            elif command == 'help':
                print_help()
            
            elif command == 'new':
                cmd_new_project(cmd_args)
            
            elif command == 'add':
                cmd_add_part(cmd_args)
            
            elif command == 'list':
                cmd_list_parts(cmd_args)
            
            elif command == 'remove':
                cmd_remove_part(cmd_args)
            
            elif command == 'info':
                cmd_info(cmd_args)
            
            elif command == 'mix':
                cmd_mix(cmd_args)
            
            elif command == 'instruments':
                cmd_instruments(cmd_args)
            
            elif command == 'scales':
                cmd_scales(cmd_args)

            elif command == 'tracks':
                cmd_tracks(cmd_args)

            elif command in ('arrangement', 'song'):
                cmd_arrangement(cmd_args)
            
            elif command == 'save':
                cmd_save(cmd_args)
            
            elif command == 'load':
                cmd_load(cmd_args)
            
            elif command == 'generate':
                cmd_generate_all(cmd_args)
            
            elif command == 'show':
                cmd_show(cmd_args)
            
            else:
                print(f"Unknown command: {command}")
                print("Type 'help' for available commands")
                
        except KeyboardInterrupt:
            print("\n")
            save_project()
            print("Project saved. Goodbye!")
            break
        except Exception as e:
            print(f"Error: {e}")
            import traceback
            traceback.print_exc()


def print_help():
    """Print help information."""
    print(f"""
{'='*60}
Studio Onyrix v4 - Commands
{'='*60}

PROJECT:
  new [name]                     Create a new project
  load <file>                    Load project from file
  save [file]                    Save project to file
  show                           Show project summary

ADDING PARTS:
  add [flags]                    Add and generate a part
    Flags:
      --instrument <name>        Instrument name (required)
      --bpm <120>                Tempo in BPM
      --division <4/4>           Time signature
      --root <C>                 Root/tonic note
      --scale <natural_minor>    Scale pattern
      --measures <8>             Number of bars
      --start <1>                Timeline start bar
      --track <bass>             Track/lane id
      --relation <verse>         Section type
      --volume <0.8>             Volume 0.0-1.0
      --pan <0.0>                Pan -1.0 to 1.0
      --temperature <1.0>        Creativity (0.5-1.5)
      --extra <text>             Extra prompt text
      --chords "Am F C G"        Set shared chord progression
      --groove <straight>        Set shared groove feel
      --swing <0.15>             Set shared swing amount
      --generate <true>          Auto-generate audio
      
    Presets (shortcuts):
      --preset <name>            Use preset (drums, bass, chords, melody, etc.)

MANAGING PARTS:
  list                           List all parts
  info <index>                   Show part details
  remove <index>                 Remove a part
  generate                       Generate all missing parts

MIXING:
  mix [--force]                  Mix all parts to audio

INFORMATION:
  instruments                    List all instruments
  scales                         List all scales
  tracks                         List project tracks
  arrangement [flags]            Set BPM/key/chords/groove/swing
  help                           Show this help
  exit                           Save and quit
""")


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    # Ensure output dir exists
    os.makedirs("output", exist_ok=True)
    
    # Load existing project if available
    ensure_project_loaded()
    
    # Parse command
    if len(sys.argv) < 2:
        # Interactive mode
        cmd_interactive([])
    else:
        command = sys.argv[1]
        cli_args = sys.argv[2:]
        
        if command == 'new':
            cmd_new_project(cli_args)
        elif command == 'part':
            cmd_add_part(cli_args)
        elif command in ('add', 'gen'):
            cmd_add_part(cli_args)
        elif command == 'list':
            cmd_list_parts(cli_args)
        elif command == 'info':
            cmd_info(cli_args)
        elif command == 'remove':
            cmd_remove_part(cli_args)
        elif command == 'mix':
            cmd_mix(cli_args)
        elif command == 'instruments':
            cmd_instruments(cli_args)
        elif command == 'scales':
            cmd_scales(cli_args)
        elif command == 'tracks':
            cmd_tracks(cli_args)
        elif command in ('arrangement', 'song'):
            cmd_arrangement(cli_args)
        elif command == 'save':
            cmd_save(cli_args)
        elif command == 'load':
            cmd_load(cli_args)
        elif command == 'generate':
            cmd_generate_all(cli_args)
        elif command == 'show':
            cmd_show(cli_args)
        elif command == 'interactive':
            cmd_interactive(cli_args)
        elif command in ('help', '--help', '-h'):
            print_help()
        else:
            print(f"Unknown command: {command}")
            print_help()
