TICKS_PER_BEAT = 480
BEATS_PER_BAR = 4
BAR_TICKS = TICKS_PER_BEAT * BEATS_PER_BAR
STEP_TICKS = TICKS_PER_BEAT // 2

ROOTS = {
    "C": 0,
    "C#": 1,
    "Db": 1,
    "D": 2,
    "D#": 3,
    "Eb": 3,
    "E": 4,
    "F": 5,
    "F#": 6,
    "Gb": 6,
    "G": 7,
    "G#": 8,
    "Ab": 8,
    "A": 9,
    "A#": 10,
    "Bb": 10,
    "B": 11,
}

CHORD_QUALITIES = {
    "": [0, 4, 7],
    "m": [0, 3, 7],
    "7": [0, 4, 7, 10],
    "maj7": [0, 4, 7, 11],
    "m7": [0, 3, 7, 10],
    "m9": [0, 3, 7, 10, 14],
    "maj9": [0, 4, 7, 11, 14],
    "dim": [0, 3, 6],
    "sus2": [0, 2, 7],
    "sus4": [0, 5, 7],
    "add9": [0, 4, 7, 14],
    "6": [0, 4, 7, 9],
    "m6": [0, 3, 7, 9],
}

INSTRUMENT_LIBRARY = {
    "drums": {"program": 0, "is_drum": True, "role": "drums", "octave": 0, "velocity": 0},
    "taiko": {"program": 116, "is_drum": False, "role": "taiko", "octave": 2, "velocity": 8},
    "bass": {"program": 34, "is_drum": False, "role": "bass", "octave": 2, "velocity": 4},
    "sub_bass": {"program": 38, "is_drum": False, "role": "bass", "octave": 1, "velocity": 8},
    "upright_bass": {"program": 32, "is_drum": False, "role": "bass", "octave": 2, "velocity": -2},
    "piano": {"program": 0, "is_drum": False, "role": "chords", "octave": 4, "velocity": 0},
    "electric_piano": {"program": 4, "is_drum": False, "role": "chords", "octave": 4, "velocity": -4},
    "guitar": {"program": 27, "is_drum": False, "role": "chords", "octave": 3, "velocity": 3},
    "pad": {"program": 89, "is_drum": False, "role": "pad", "octave": 4, "velocity": -12},
    "strings": {"program": 48, "is_drum": False, "role": "pad", "octave": 4, "velocity": -6},
    "pluck": {"program": 80, "is_drum": False, "role": "arp", "octave": 4, "velocity": -5},
    "lead": {"program": 81, "is_drum": False, "role": "melody", "octave": 5, "velocity": 2},
    "sax_lead": {"program": 65, "is_drum": False, "role": "melody", "octave": 4, "velocity": 4},
    "bell": {"program": 14, "is_drum": False, "role": "arp", "octave": 5, "velocity": -8},
    "choir": {"program": 52, "is_drum": False, "role": "pad", "octave": 4, "velocity": -10},
}

STYLE_LIBRARY = {
    "lofi": {
        "bpm": 78,
        "tracks": ["drums", "bass", "electric_piano", "pad", "lead"],
        "chords": ["Cmaj7", "Am7", "Fmaj7", "G"],
        "swing": 0.18,
        "density": 0.55,
        "humanize": 12,
        "drum_groove": "laidback",
        "melody_shape": "small_steps",
    },
    "jazz": {
        "bpm": 120,
        "tracks": ["drums", "upright_bass", "piano", "sax_lead"],
        "chords": ["Dm7", "G7", "Cmaj7", "Am7"],
        "swing": 0.26,
        "density": 0.7,
        "humanize": 14,
        "drum_groove": "ride",
        "melody_shape": "bebop",
    },
    "cinematic": {
        "bpm": 92,
        "tracks": ["taiko", "bass", "strings", "pad", "piano", "lead"],
        "chords": ["Am", "F", "C", "G"],
        "swing": 0.03,
        "density": 0.5,
        "humanize": 8,
        "drum_groove": "cinematic",
        "melody_shape": "wide",
    },
    "ambient": {
        "bpm": 70,
        "tracks": ["pad", "piano", "strings", "lead"],
        "chords": ["Fmaj7", "Cmaj7", "G", "Am"],
        "swing": 0.02,
        "density": 0.3,
        "humanize": 16,
        "drum_groove": "none",
        "melody_shape": "sparse",
    },
    "edm": {
        "bpm": 128,
        "tracks": ["drums", "sub_bass", "pluck", "pad", "lead"],
        "chords": ["C", "G", "Am", "F"],
        "swing": 0.04,
        "density": 0.8,
        "humanize": 5,
        "drum_groove": "four_on_floor",
        "melody_shape": "hook",
    },
    "trap": {
        "bpm": 140,
        "tracks": ["drums", "sub_bass", "pluck", "pad", "lead"],
        "chords": ["Am", "F", "Dm", "E"],
        "swing": 0.08,
        "density": 0.75,
        "humanize": 7,
        "drum_groove": "trap",
        "melody_shape": "minor_hook",
    },
    "synthwave": {
        "bpm": 100,
        "tracks": ["drums", "sub_bass", "pad", "pluck", "lead"],
        "chords": ["Am", "F", "Dm", "E"],
        "swing": 0.02,
        "density": 0.68,
        "humanize": 6,
        "drum_groove": "retro",
        "melody_shape": "neon",
    },
    "rock": {
        "bpm": 118,
        "tracks": ["drums", "bass", "guitar", "piano", "lead"],
        "chords": ["E", "A", "C#m", "B"],
        "swing": 0.03,
        "density": 0.72,
        "humanize": 7,
        "drum_groove": "rock",
        "melody_shape": "anthem",
    },
    "funk": {
        "bpm": 108,
        "tracks": ["drums", "bass", "electric_piano", "guitar", "lead"],
        "chords": ["Dm7", "G7", "Em7", "A7"],
        "swing": 0.12,
        "density": 0.85,
        "humanize": 10,
        "drum_groove": "funk",
        "melody_shape": "syncopated",
    },
    "techno": {
        "bpm": 132,
        "tracks": ["drums", "sub_bass", "pluck", "pad", "lead"],
        "chords": ["Fm", "Db", "Ab", "Eb"],
        "swing": 0.02,
        "density": 0.78,
        "humanize": 4,
        "drum_groove": "four_on_floor",
        "melody_shape": "minimal",
    },
    "classical": {
        "bpm": 96,
        "tracks": ["piano", "strings", "bass", "lead"],
        "chords": ["C", "G", "Am", "F"],
        "swing": 0.0,
        "density": 0.58,
        "humanize": 9,
        "drum_groove": "none",
        "melody_shape": "lyrical",
    },
}

MOOD_LIBRARY = {
    "happy": {"velocity": 8, "octave": 0, "density": 0.08, "brightness": 6},
    "sad": {"velocity": -8, "octave": -1, "density": -0.05, "brightness": -8},
    "dark": {"velocity": -4, "octave": -1, "density": 0.02, "brightness": -10},
    "dreamy": {"velocity": -6, "octave": 1, "density": -0.12, "brightness": 2},
    "energetic": {"velocity": 12, "octave": 0, "density": 0.16, "brightness": 8},
    "romantic": {"velocity": -2, "octave": 0, "density": -0.03, "brightness": 1},
    "epic": {"velocity": 14, "octave": 0, "density": 0.1, "brightness": 4},
    "melancholic": {"velocity": -7, "octave": -1, "density": -0.02, "brightness": -6},
    "aggressive": {"velocity": 16, "octave": -1, "density": 0.18, "brightness": 5},
    "peaceful": {"velocity": -10, "octave": 1, "density": -0.18, "brightness": -1},
}

SECTION_LIBRARY = [
    {"name": "intro", "start": 0.0, "end": 0.125, "velocity": -14, "density": -0.18},
    {"name": "verse", "start": 0.125, "end": 0.375, "velocity": -4, "density": -0.04},
    {"name": "lift", "start": 0.375, "end": 0.5, "velocity": 4, "density": 0.04},
    {"name": "hook", "start": 0.5, "end": 0.75, "velocity": 12, "density": 0.14},
    {"name": "outro", "start": 0.875, "end": 1.0, "velocity": -12, "density": -0.16},
]

DRUM_NOTES = {
    "kick": 36,
    "snare": 38,
    "closed_hat": 42,
    "open_hat": 46,
    "clap": 39,
    "ride": 51,
    "tom_low": 45,
}
